-- MySQL Script generated by MySQL Workbench
-- Tue May 21 20:07:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `tp_programacion3` DEFAULT CHARACTER SET utf8 ;
USE `tp_programacion3` ;

-- -----------------------------------------------------
-- Table `habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_programacion3`.`habitaciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(15) NOT NULL,
  `COSTO` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_programacion3`.`registros` (
  `IDREGISTROS` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL,
  `TIPO` VARCHAR(15) NOT NULL,
  `COSTO` INT NOT NULL,
  `DIAS` INT NOT NULL,
  `PAGO` VARCHAR(2) NOT NULL,
  `SUBTOTAL` INT NOT NULL,
  `DESCUENTO` INT NOT NULL,
  `TOTAL` INT NOT NULL,
  `ESTADO` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDREGISTROS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_programacion3`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `salt` VARCHAR(64) NOT NULL,´
  `estado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
